<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'New password' => 'New password',
    '... when a person stops reading, he stops thinking ...' => '... when a person stops reading, he stops thinking ...',
    'About' => 'About',
    'Authors' => 'Authors',
    'Books' => 'Books',
    'Captcha' => 'Captcha',
    'Contact us' => 'Contact us',
    'Email' => 'E-mail',
    'FAQ' => 'FAQ',
    'Genres' => 'Genres',
    'Home' => 'Home',
    'If you forgot your password you can ' => 'If you forgot your password you can ',
    'Logout' => 'Logout',
    'My Company' => 'ReadMe-f',
    'Name' => 'Name',
    'Password' => 'Password',
    'Please choose your new password:' => 'Please choose your new password:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Please fill out your email. A link to reset password will be sent there.',
    'Publishing Houses' => 'Publishing Houses',
    'Request password reset' => 'Request password reset',
    'Reset password' => 'Reset password',
    'Save' => 'Save',
    'Send' => 'Send',
    'Sign into the system' => 'Sign into the system',
    'SignIn' => 'Sign in',
    'SignUp' => 'Sign up',
    'Signin' => 'Signin',
    'Signup' => 'Signup',
    'Subject' => 'Subject',
    'Text' => 'Text',
    'Top-100' => 'Top-100',
    'Username' => 'Username',
    'online library' => 'online library',
    'reset it' => 'reset it',
];
