<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'New password' => 'Новий пароль',
    '... when a person stops reading, he stops thinking ...' => '... коли людина припиняє читати, вона перестає мислити ...',
    'About' => 'Про нас',
    'Authors' => 'Автори',
    'Books' => 'Книги',
    'Captcha' => 'Антиробот',
    'Contact us' => 'Напишіть нам',
    'Email' => 'E-mail',
    'FAQ' => 'FAQ',
    'Genres' => 'Жанри',
    'Home' => 'Головна',
    'If you forgot your password you can ' => 'Якщо Ви забули свій пароль Ви можете ',
    'Logout' => 'Вийти',
    'My Company' => 'Прочитай мене (front)',
    'Name' => 'Ім’я',
    'Password' => 'Пароль',
    'Please choose your new password:' => 'Будь ласка, введіть Ваш новий пароль:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Будь ласка, введіть електронну пошту, на неї буде вислане посилання для зміни паролю.',
    'Publishing Houses' => 'Видавництва',
    'Request password reset' => 'Запит на зміну пароля',
    'Reset password' => 'Зміна паролю',
    'Save' => 'Зберегти',
    'Send' => 'Відправити',
    'Sign into the system' => 'Вхід в систему',
    'SignIn' => 'Вхід',
    'SignUp' => 'Реєстрація',
    'Signin' => 'Ввійти',
    'Signup' => 'Зареєструватися',
    'Subject' => 'Тема',
    'Text' => 'Текст',
    'Top-100' => 'Топ-100',
    'Username' => 'Логін',
    'online library' => 'онлайн-бібліотека',
    'reset it' => 'відновити його',
];
