<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'New password' => 'Новый пароль',
    '... when a person stops reading, he stops thinking ...' => '... когда человек прекращает читать, он перестает мыслить ...',
    'About' => 'О нас',
    'Authors' => 'Авторы',
    'Books' => 'Книги',
    'Captcha' => 'Антиробот',
    'Contact us' => 'Напишите нам',
    'Email' => 'E-mail',
    'FAQ' => 'ЧАВО',
    'Genres' => 'Жанры',
    'Home' => 'Главная',
    'If you forgot your password you can ' => 'Если Вы забыли свой пароль Вы можете ',
    'Logout' => 'Выйти',
    'My Company' => 'Прочти меня-f',
    'Name' => 'Имя',
    'Password' => 'Пароль',
    'Please choose your new password:' => 'Пожалуйста, введите Ваш новый пароль:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Пожалуйста, введите электронную почту, на нее будет выслана ссылка для сброса пароля.',
    'Publishing Houses' => 'Издательства',
    'Request password reset' => 'Запрос на сброс пароля',
    'Reset password' => 'Сброс пароля',
    'Save' => 'Сохранить',
    'Send' => 'Отправить',
    'Sign into the system' => 'Вход в систему',
    'SignIn' => 'Вход',
    'SignUp' => 'Регистрация',
    'Signin' => 'Войти',
    'Signup' => 'Зарегистрироваться',
    'Subject' => 'Тема',
    'Text' => 'Текст',
    'Top-100' => 'Топ-100',
    'Username' => 'Логин',
    'online library' => 'онлайн-библиотека',
    'reset it' => 'восстановить его',
];
